In [1]:
import numpy as np
import pandas as pd

# Format of multiple time series: (n_ts,sz,d), where n: number of main time series, sz: number of points per sub time series, d: number of dimensions per main time series
# Here: (2,4,2)
arr = np.array([[[1,4],
                 [2,5],
                 [3,6],
                 [4,4]], [[3,4],
                          [4,5],
                          [3,2],
                          [3,3]]])

# Create data frame from one multi-dimensional time series
df = pd.DataFrame(arr[0])
df

0  1
0  1  4
1  2  5
2  3  6
3  4  4

In [2]:
type(df.values)

numpy.ndarray

In [3]:
# Convert dataframe back to 2d numpy array
df.values

array([[1, 4],
       [2, 5],
       [3, 6],
       [4, 4]])

In [4]:
# Stick multiple 2d numpy arrays to 3d numpy array
arr1 = np.array([[55,44],[33,44],[44,22],[23,32]])
np.stack([df.values, arr1], axis=0)

array([[[ 1,  4],
        [ 2,  5],
        [ 3,  6],
        [ 4,  4]],

       [[55, 44],
        [33, 44],
        [44, 22],
        [23, 32]]])

In [5]:
# Stick multiple time series in a data frame together
# In this dataframe, we have 2 main time series, each with 2 dimensions and 4 data points
df_concat = pd.concat([df, pd.DataFrame(arr[1])], axis=1)
df_concat

0  1  0  1
0  1  4  3  4
1  2  5  4  5
2  3  6  3  2
3  4  4  3  3

In [6]:
np.array(arr.shape)
df_concat.iloc[:,1:55].to_numpy()

array([[4, 3, 4],
       [5, 4, 5],
       [6, 3, 2],
       [4, 3, 3]])

In [7]:
def segmentation(ts_size, window_size):
    bounds = np.arange(0,ts_size+1,window_size)
    # if in last (partial) window more than half of window size are included, then include those points
    if ts_size % window_size > window_size / 2:
        bounds = np.append(bounds, ts_size)
    start = bounds[:-1]
    end = bounds[1:]
    size = start.size
    return start, end, size

In [8]:
start,end,size=segmentation(10,3)
size

3

In [9]:
X = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
segment = X[0, 0:2, :]
segment

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
def transform(X, window_size):
    n_ts, sz, d = X.shape
    start, end, n_timestamps_new = segmentation(sz, window_size)
    X_transformed = np.empty((n_ts, n_timestamps_new, d))
    for i_ts in range(n_ts):
        for i_seg in range(n_timestamps_new):
            segment = X[i_ts, start[i_seg]:end[i_seg], :]
            X_transformed[i_ts, i_seg, :] = segment.mean(axis=0)
    return X_transformed

In [11]:
X=np.array([[[1,2],
             [3,4],
             [5,6],
             [7,8],
             [1,2],
             [3,4],
             [5,6],
             [7,8],
             [1,2],
             [3,4],
             [5,6]], [[1,2],
                      [3,4],
                      [5,6],
                      [7,8],
                      [1,2],
                      [3,4],
                      [5,6],
                      [7,8],
                      [1,2],
                      [3,4],
                      [5,6]]])
transform(X,3)

array([[[3.        , 4.        ],
        [3.66666667, 4.66666667],
        [4.33333333, 5.33333333],
        [4.        , 5.        ]],

       [[3.        , 4.        ],
        [3.66666667, 4.66666667],
        [4.33333333, 5.33333333],
        [4.        , 5.        ]]])

In [12]:
X

array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8],
        [1, 2],
        [3, 4],
        [5, 6],
        [7, 8],
        [1, 2],
        [3, 4],
        [5, 6]],

       [[1, 2],
        [3, 4],
        [5, 6],
        [7, 8],
        [1, 2],
        [3, 4],
        [5, 6],
        [7, 8],
        [1, 2],
        [3, 4],
        [5, 6]]])